import raw from '@/data/manifest.json'

/**
 * The release manifest, as the wiki reads it.
 *
 * `manifest.json` is generated by CI in the `automation-forge` repository from
 * the plugin register, the plugin descriptors and the published GitHub
 * releases. It is the only thing that knows every version that exists, what it
 * weighs, its sha256 and its release notes.
 *
 * The rule this file exists to enforce: **the wiki never restates a number the
 * manifest already knows.** No page types a version, a download URL or a
 * release date. If you catch yourself writing one in MDX, read it from here
 * instead — a number typed twice drifts, and this family has lost days to
 * exactly that.
 *
 * `tools/sync-manifest.mjs` refreshes `data/manifest.json`; it refuses a
 * schemaVersion this file was not written against.
 */

export type Channel = 'stable' | 'nightly'

/** What the register decides per plugin. See the distribution page. */
export type Distribution = 'open' | 'fab' | 'paid'

export type Role = 'core' | 'provider' | 'addon' | 'adapter' | 'toolset' | 'post' | 'app'

export type ManifestVersion = {
  version: string
  engine: string
  platform: string
  channel: Channel
  url: string
  size: number
  sha256: string
  symbols?: string | null
  releasedAt: string
  notes?: string | null
}

export type ChangelogEntry = {
  version: string
  date: string
  body: string
}

export type ManifestPlugin = {
  id: string
  set: string
  role: Role
  distribution: Distribution
  dependencies: string[]
  /** The public mirror, for `open` plugins. Null for everything else. */
  source: string | null
  versions: ManifestVersion[]
  changelog: ChangelogEntry[]
}

export type ManifestSet = {
  id: string
  name: string
  members: string[]
}

export type Manifest = {
  schemaVersion: number
  generatedAt: string
  releases: string
  channels: Channel[]
  sets: ManifestSet[]
  plugins: ManifestPlugin[]
}

export const manifest = raw as unknown as Manifest

export const generatedAt = manifest.generatedAt
export const releasesRepo = manifest.releases

const byId = new Map(manifest.plugins.map((p) => [p.id, p]))
const setsById = new Map(manifest.sets.map((s) => [s.id, s]))

export function plugin(id: string): ManifestPlugin | undefined {
  return byId.get(id)
}

export function set(id: string): ManifestSet | undefined {
  return setsById.get(id)
}

/** Every plugin belonging to a set, in register order. */
export function membersOf(setId: string): ManifestPlugin[] {
  const s = setsById.get(setId)
  if (!s) return []
  return s.members.map((m) => byId.get(m)).filter((p): p is ManifestPlugin => !!p)
}

/**
 * The newest stable version of a plugin, or undefined if it has never been
 * released. Unreleased is a real state — several plugins exist in the register
 * and have shipped nothing — and the caller must render it as such rather than
 * fall back to a plausible-looking number.
 */
export function latest(id: string, channel: Channel = 'stable'): ManifestVersion | undefined {
  const p = byId.get(id)
  if (!p) return undefined
  return p.versions
    .filter((v) => v.channel === channel)
    .sort((a, b) => compareVersions(b.version, a.version))[0]
}

/** The newest release across a whole set — what "MotionForge 0.4.0" means. */
export function latestInSet(setId: string): { plugin: ManifestPlugin; version: ManifestVersion } | undefined {
  let best: { plugin: ManifestPlugin; version: ManifestVersion } | undefined
  for (const p of membersOf(setId)) {
    const v = latest(p.id)
    if (!v) continue
    if (!best || Date.parse(v.releasedAt) > Date.parse(best.version.releasedAt)) {
      best = { plugin: p, version: v }
    }
  }
  return best
}

export function compareVersions(a: string, b: string): number {
  const pa = a.split('.').map(Number)
  const pb = b.split('.').map(Number)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0)
    if (d !== 0) return d
  }
  return 0
}

export type ReleaseEvent = {
  pluginId: string
  setId: string
  setName: string
  distribution: Distribution
  role: Role
  version: string
  releasedAt: string
  notes?: string | null
  url: string
  size: number
  body?: string
}

/**
 * Every published version of every plugin as one reverse-chronological feed —
 * the release log, assembled rather than written.
 *
 * A `paid` plugin publishes to a private repository, so its download URL is
 * not something a visitor can follow. Its *existence* and its notes are still
 * public facts and belong in the log; the page is responsible for not offering
 * a link that would 404 for everyone but us.
 */
export function releaseFeed(): ReleaseEvent[] {
  const events: ReleaseEvent[] = []
  for (const p of manifest.plugins) {
    const s = setsById.get(p.set)
    const notesByVersion = new Map(p.changelog.map((c) => [c.version, c.body]))
    for (const v of p.versions) {
      if (v.channel !== 'stable') continue
      events.push({
        pluginId: p.id,
        setId: p.set,
        setName: s?.name ?? p.set,
        distribution: p.distribution,
        role: p.role,
        version: v.version,
        releasedAt: v.releasedAt,
        notes: v.notes,
        url: v.url,
        size: v.size,
        body: notesByVersion.get(v.version),
      })
    }
  }
  return events.sort((a, b) => Date.parse(b.releasedAt) - Date.parse(a.releasedAt))
}

export function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}
